spring:
  redis:
    host: localhost 
    port: 6379
    password: Ay1ZwVVeVsHIHnPh0g9LyjQHsOHiqYgWqVsXSZQPAkw=
    auth: false
  main:
    allow-circular-references: true
    
    
server:
  servlet:
    session:
      timeout: 300
    context-path: /ratelimit

  
app:
  users:
    - user1
    - user2
    - user3
    - user4


api:
  max:
    requests:
      minute: 20
  default:
    requests:
      minute: 5