spring:
  redis:
    host: localhost 
    port: 6379
    password: admin
  main:
    allow-circular-references: true
  session:
    redis:
      flush-mode: on-save
      namespace: "{spring:session}"
    
server:
  servlet:
    session:
      timeout: 300
#    context-path: /ratelimit

  
api:
  max:
    requests:
        standard:
          minute: 5
        premium:
          minute: 15